local PLUGIN = CAdmin.Plugins.Create ("Fun")
PLUGIN:SetAuthor ("!cake")
PLUGIN:SetDescription ("Provides commands for setting hp, etc.")

function PLUGIN:Initialize ()
	local command = CAdmin.Commands.Create ("cloak", "Fun", "Cloak", true)
		:SetConsoleCommand ("cloak")
		:SetLogString ("%Player% cloaked %target%.")
		:SetReverseConsoleCommand ("uncloak")
		:SetReverseDisplayName ("Uncloak")
		:SetReverseLogString ("%Player% uncloaked %target%.")
	command:AddArgument ("Player", "Player", "^")
		:SetPromptText ("Select whom you want to cloak:")
		:SetReversePromptText ("Select whom you want to uncloak:")
	command:SetExecute (function (ply, targply, cloak)
	end)

	command = CAdmin.Commands.Create ("god", "Fun", "God", true)
		:SetConsoleCommand ("god")
		:SetLogString ("%Player% godded %target%.")
		:SetReverseConsoleCommand ("ungod")
		:SetReverseDisplayName ("Ungod")
		:SetReverseLogString ("%Player% ungodded %target%.")
	command:AddArgument ("Player", "Player", "^")
		:SetPromptText ("Select whom you want to god:")
		:SetReversePromptText ("Select whom you want to ungod:")
	command:SetExecute (function (ply, targply, god)
		if god then
			ply:GodEnable ()
		else
			ply:GodDisable ()
		end
		CAdmin.Players.SetSessionData (ply, "Invincible", god, true)
	end)
	command:SetGetToggleState (function (ply)
		return CAdmin.Players.GetSessionData (ply, "Invincible")
	end)

	command = CAdmin.Commands.Create ("noclip", "Fun", "Noclip", true)
		:SetConsoleCommand ("noclip")
		:SetLogString ("%Player% put %target% in noclip.")
		:SetReverseConsoleCommand ("unnoclip")
		:SetReverseDisplayName ("Unnoclip")
		:SetReverseLogString ("%Player% unnoclipped %target%.")
	command:AddArgument ("Player", "Player", "^")
		:SetPromptText ("Select whom you want to noclip:")
		:SetReversePromptText ("Select whom you want to unnoclip:")
	command:SetExecute (function (ply, targply, noclip)
		targply:SetMoveType (noclip and MOVETYPE_NOCLIP or MOVETYPE_WALK)
		CAdmin.Timers.RunAfter (targply:Ping () * 0.002, function ()
			CAdmin.RPC.FireEvent ("CAdminCommandToggleStatesChanged")
		end)
	end)
	command:SetGetToggleState (function (targply)
		return targply:GetMoveType () == MOVETYPE_NOCLIP
	end)
	
	command = CAdmin.Commands.Create ("set_armor", "Fun", "Set Armor")
		:SetConsoleCommand ("armor")
		:SetLogString ("%Player% set the armor of %target% to %arg1%.")
	command:AddArgument ("Player", "Player", "^")
		:SetPromptText ("Select whom you want to set armor for:")
	command:AddArgument ("Number", "Armor")
		:SetPromptText ("Enter armor:")
		:SetParameter ("Minimum", 0)
		:SetParameter ("Maximum", 32767)
	command:SetExecute (function (ply, targply, armor)
		targply:SetArmor (armor)
	end)
	
	command = CAdmin.Commands.Create ("set_hp", "Fun", "Set Health")
		:SetConsoleCommand ("hp")
		:SetLogString ("%Player% set the health of %target% to %arg1%.")
	command:AddArgument ("Player", "Player", "^")
		:SetPromptText ("Select whom you want to set health for:")
	command:AddArgument ("Number", "Health")
		:SetPromptText ("Enter health:")
		:SetParameter ("Minimum", 1)
		:SetParameter ("Maximum", 2147483647)
	command:SetExecute (function (ply, targply, health)
		targply:SetHealth (health)
	end)
end